# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.14

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /GPUFS/sysu_hpcedu_302/asc20/zzc/download/spack-0.16.0/opt/spack/linux-centos7-skylake_avx512/gcc-8.3.0/cmake-3.14.0-bissyyhhdx7nofcthkiz7n545ztzq2zm/bin/cmake

# The command to remove a file.
RM = /GPUFS/sysu_hpcedu_302/asc20/zzc/download/spack-0.16.0/opt/spack/linux-centos7-skylake_avx512/gcc-8.3.0/cmake-3.14.0-bissyyhhdx7nofcthkiz7n545ztzq2zm/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /GPUFS/sysu_hpcedu_302/asc20/zzc/code/scalableIndex/learned_index_benchmark_3

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /GPUFS/sysu_hpcedu_302/asc20/zzc/code/scalableIndex/learned_index_benchmark_3

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/GPUFS/sysu_hpcedu_302/asc20/zzc/download/spack-0.16.0/opt/spack/linux-centos7-skylake_avx512/gcc-8.3.0/cmake-3.14.0-bissyyhhdx7nofcthkiz7n545ztzq2zm/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/GPUFS/sysu_hpcedu_302/asc20/zzc/download/spack-0.16.0/opt/spack/linux-centos7-skylake_avx512/gcc-8.3.0/cmake-3.14.0-bissyyhhdx7nofcthkiz7n545ztzq2zm/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /GPUFS/sysu_hpcedu_302/asc20/zzc/code/scalableIndex/learned_index_benchmark_3/CMakeFiles /GPUFS/sysu_hpcedu_302/asc20/zzc/code/scalableIndex/learned_index_benchmark_3/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /GPUFS/sysu_hpcedu_302/asc20/zzc/code/scalableIndex/learned_index_benchmark_3/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named microbench

# Build rule for target.
microbench: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 microbench
.PHONY : microbench

# fast build rule for target.
microbench/fast:
	$(MAKE) -f CMakeFiles/microbench.dir/build.make CMakeFiles/microbench.dir/build
.PHONY : microbench/fast

microbench.o: microbench.cpp.o

.PHONY : microbench.o

# target to build an object file
microbench.cpp.o:
	$(MAKE) -f CMakeFiles/microbench.dir/build.make CMakeFiles/microbench.dir/microbench.cpp.o
.PHONY : microbench.cpp.o

microbench.i: microbench.cpp.i

.PHONY : microbench.i

# target to preprocess a source file
microbench.cpp.i:
	$(MAKE) -f CMakeFiles/microbench.dir/build.make CMakeFiles/microbench.dir/microbench.cpp.i
.PHONY : microbench.cpp.i

microbench.s: microbench.cpp.s

.PHONY : microbench.s

# target to generate assembly for a file
microbench.cpp.s:
	$(MAKE) -f CMakeFiles/microbench.dir/build.make CMakeFiles/microbench.dir/microbench.cpp.s
.PHONY : microbench.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... microbench"
	@echo "... edit_cache"
	@echo "... microbench.o"
	@echo "... microbench.i"
	@echo "... microbench.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

